import "./globals.css"

export const metadata = {
  title: "Ermahgerd!",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <h1 className="text-2xl font-semibold">Sperterfer!</h1>
        {children}
      </body>
    </html>
  )
}
